const router = require('express').Router()
const user = require('./user')
const map = require('./map')
const shorturl = require('./shorturl')
const search = require('./search')
const checkPeople = require('./checkPeople')
router.use('/user',user)
router.use('/map',map)
router.use('/shorturl',shorturl)
router.use('/search',search)
router.use('/checkPeople',checkPeople)
module.exports = router